import type { Project } from '@/components/ProjectCard'

export const projects: Project[] = [
  {
    title: 'GeoGuessrのめも',
    description: '2023年はじめから不定期に更新しているジオゲッサーのプレイログです。',
    href: 'https://geopinning.space/rule/',
    tags: ['HTML', 'Game', 'Research'],
    category: 'hobby',
    image: '/thumbnails/geopinning.png',
  },
  {
    title: 'めも',
    description: '2011年頃から不定期更新している個人ブログ。',
    href: 'https://paper.hatenadiary.jp/',
    tags: ['Blog'],
    category: 'hobby',
    image: '/thumbnails/memo-main.png',
  },
  {
    title: '生活に関するめも',
    description: '2020年頃から不定期更新している経済関係のブログ。',
    href: 'https://paper-log.hatenadiary.jp/',
    tags: ['Blog'],
    category: 'hobby',
    image: '/thumbnails/memo-ec.png',
  },
  {
    title: 'K_DM',
    description: '2020年頃に機械学習の勉強用に作成したウェブサイト＋動画。',
    href: 'https://www.youtube.com/@K_DM',
    tags: ['Machine Learning', 'Study'],
    category: 'study',
    image: '/thumbnails/k_dm.png',
  },
  {
    title: '機械学習のめも帳',
    description: '2018年頃に作成した自習用ウェブサイト。',
    href: 'https://k-dm.work/',
    tags: ['Machine Learning', 'Study', 'Python'],
    category: 'study',
    image: '/thumbnails/memo-ml.png',
  },
  {
    title: 'MK8DX6v6(交流戦)即時集計',
    description: '2017年に作成したMK8D用即時集計器。',
    href: 'https://paper-web.sakura.ne.jp/sokuji/sokuji.html',
    tags: ['Game'],
    category: 'others',
    image: '/thumbnails/mk8d.png',
  },
  {
    title: 'Twitch',
    description: '不定期でゲーム配信しています。',
    href: 'https://www.twitch.tv/nanjakorewa',
    tags: ['Streaming'],
    category: 'hobby',
    image: '/thumbnails/twitch.png',
  },
  {
    title: 'Youtube',
    description: '不定期で動画投稿しています。',
    href: 'https://www.youtube.com/@nanjakorewa',
    tags: ['Streaming'],
    category: 'hobby',
    image: '/thumbnails/youtube.png',
  },
  {
    title: 'X',
    description: 'Xメインアカウント。',
    href: 'https://x.com/nanjakorewa',
    tags: ['daily'],
    category: 'hobby',
    image: '/thumbnails/x.png',
  },
]
